site_name: Profiti kasutusjuhend
docs_dir: src/docs
site_dir: docs
theme:
      name: material
      custom_dir : overrides
      # language: et
      icon:
            admonition:
                  note: octicons/tag-16
                  abstract: octicons/checklist-16
                  info: octicons/info-16
                  tip: octicons/squirrel-16
                  success: octicons/check-16
                  question: octicons/question-16
                  warning: octicons/alert-16
                  failure: octicons/x-circle-16
                  danger: octicons/zap-16
                  bug: octicons/bug-16
                  example: octicons/beaker-16
                  quote: octicons/quote-16
      features:
            - content.code.select
            - content.code.copy
            - content.code.annotate 
            - navigation.footer
            - navigation.indexes
            - navigation.top
            - content.tooltips
            # - toggle
      palette:
            - scheme: default
            #   primary: green
            #   accent: indigo
              toggle:
                  icon: material/weather-night
                  name: Switch to dark mode
            - scheme: slate
            #   primary: blue
            #   accent: indigo
              toggle:
                  icon: material/weather-sunny
                  name: Switch to light mode            
extra_css:
  - stylesheets/extra.css

copyright: <a href="https://intellisoft.ee">Copyright &copy; 2002 - 2026 Intellisoft OÜ</a>

markdown_extensions:
      - pymdownx.keys
      - pymdownx.highlight:
            anchor_linenums: true
            line_spans: __span
            pygments_lang_class: true
      - pymdownx.inlinehilite
      #  - pymdownx.snippets
      #  - pymdownx.superfences
      - admonition
      - pymdownx.details
      - pymdownx.superfences:
            custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format      #  - attr_list
      - md_in_html
      - attr_list
      - pymdownx.emoji:
            emoji_index: !!python/name:material.extensions.emoji.twemoji
            emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
      - search
      - glightbox
      - mkdocs-nav-weight:
            section_renamed: false
            index_weight: -10
            warning: true
            reverse: false
      # - typeset
      # - blog:
      #       post_excerpt: optional
      #       post_url_format: "{slug}"
      #       archive_name: Arhiiv
      #       categories_name: Kategooriad
      #       categories_allowed:
      #             - Uuendused
      #             - Küsimused
      #             - Muud
      #             - Päevik

      - i18n:
            languages:
                  - locale: et
                    name: Eesti
                    default: true
                  - locale: en
                    name: English
                    site_name: Profit ERP User Guide
                    nav_translations:
                        'Üldine': 'General'
                        'Valuutad': 'Currencies'
                        'Töö alustamine': 'Getting started'
                        'Kasutajaliides': 'User interface'
                        'Üldkasutatavad registrid': 'Common registries'
                        'Firmad': 'Companies'
                        'Müük': 'Sales'
                        'Ost': 'Purchases'
                        'Küsimused': 'FAQ'
                        'Blogi': 'Blog'
                        'Versioonid': 'Versions'
                  - locale: ru
                    name: Русский
                    site_name: Руководство пользователя Profit ERP
                    nav_translations:
                        'Üldine': 'Общее'
                        'Valuutad': 'Валюты'
                        'Töö alustamine': 'Начало работы'
                        'Kasutajaliides': 'Пользовательский интерфейс'
                        'Üldkasutatavad registrid': 'Общие регистры'
                        'Firmad': 'Компании'
                        'Müük': 'Продажи'
                        'Ost': 'Покупки'
                        'Küsimused': 'Вопросы'
                        'Blogi': 'Блог'
                        'Versioonid': 'Версии'



extra:
      social:
            - icon: material/home
              link: https://profit24.eu
              name: Profit ERP landing page
            - icon: material/web
              link: https://app.profit24.eu
              name: Profit ERP
            - icon: material/email
              link: mailto:help@intellisoft.ee
              name: Contact us
            - icon: material/phone
              link: tel:+3725104059
              name: +372 5104 059
            - icon: fontawesome/brands/youtube
              link: https://www.youtube.com/channel/UCvj7n6TYE7hMERJXqI3FO2g
              name: Video tutorials
            - icon: fontawesome/brands/facebook
              link: https://www.facebook.com/profit-tarkvara
              name: Profit Facebook page
              
nav:
      - 'index.md'
      - Üldine:
            - 'currencies/index.md'
      - 'Töö alustamine':
            - Töö alustamine: 'start/index.md'
            - 'start/register.md'
            - 'start/create-db.md'
            - 'start/access-other-company.md'
            - 'start/my-companies.md'
            - 'start/primary-settings.md'
            - 'start/user-settings.md'
            - 'start/user-setup-email.md'
      - Kasutajaliides:
            - Kasutajaliides: 'ui/index.md'
            - 'ui/colorscheme.md'
            - 'ui/doc_sidepanel.md'
      - Üldkasutatavad registrid:
            - Firmad: 'registries/companies.md'
      - Müük: 
            - 'sales/index.md'
            - 'sales/salesinvoices.md'
            - 'sales/salesorders.md'
      - Ost:
            - 'purchases/index.md'
            - 'purchaseinvoices.md'
            - 'purchases/tasumised.md'
      - Finants:
            - 'accounting/index.md'
            - 'accounting/general_ledger.md'

            - 'accounting/gl_settlements_history.md'
      - Küsimused:
            - 'faq/index.md'
            - 'faq/tasaarveldused.md'
      - Versioonid:
            - versions/index.md
            - versions/0.65.md
            - versions/0.64.md
            - versions/0.63.md
            - versions/0.51.md
            - versions/0.50.md
            - versions/0.49.md
            - versions/0.48.md
            - versions/0.47.md
            - versions/0.46.md
            - versions/0.45.md


